---
- hosts: "localhost"
  tasks:
  - add_host: name="{{ host | default('localhost')}}"
- hosts: "{{ host | default('localhost')}}"
  become: yes
  tasks:
  - apt: name=snapd state=latest
  #- snap: name=microk8s
  - shell: microk8s.stop || true
  - shell: snap install --classic microk8s
  - shell: microk8s.start
  - pause: seconds=45
  - shell: microk8s.enable dns dashboard storage ingress gpu registry
